# Copyright 2023 LiveKit, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Bump and publish crates

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      packages:
        description: "packages to bump (comma-separated list)"
        type: string
        required: true
  pull_request:
    types: [closed]
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

jobs:
  bump:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.NANPA_KEY }}
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        
      - name: Prepare packages for ilo
        id: prepare_packages
        run: |
          # Check if this is a manual workflow run or push trigger
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Create an array from comma-separated list provided by user
            IFS=',' read -ra PKG_ARRAY <<< "${{ github.event.inputs.packages }}"
            
            # Convert to JSON format with explicit wrapping
            JSON_ARRAY=$(printf '%s\n' "${PKG_ARRAY[@]}" | jq -R . | jq -s .)
            echo "Workflow dispatch with packages: ${PKG_ARRAY[*]}"
          else
            # For push events, use an empty array (no packages to bump)
            # This effectively makes the workflow run but not perform any version bumps
            JSON_ARRAY="[]"
            echo "Push trigger - using empty package list"
          fi
          
          echo "Formatted packages JSON: $JSON_ARRAY"
          
          # Save to a file that ilo can read - ensure we preserve quotes and formatting
          echo "$JSON_ARRAY" > packages.json
          
      - name: Debug packages.json content
        run: |
          echo "Raw file content:"
          cat packages.json
          echo "JSON validation check:"
          jq '.' packages.json || echo "Invalid JSON detected"
          
      - name: Use ilo with packages file
        uses: nbsp/ilo@v1
        with:
          packages: '[]'
  publish:
    runs-on: ubuntu-latest
    needs: bump
    permissions:
      contents: write
    outputs:
      published_crates: ${{ steps.publish.outputs.published_crates }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Resync is needed after bump
        run: |
          git fetch --tags && git checkout origin/main
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Configure Cargo Registry
        run: |
          mkdir -p ~/.cargo
          # Create main config file
          cat > ~/.cargo/config.toml << EOF
          [registries.quantum-forge]
          index = "https://crate-registry.quantum-forge.io"
          
          [net]
          git-fetch-with-cli = true
          retry = 5
          
          [http]
          timeout = 120
          check-revoke = false
          multiplexing = false
          
          [term]
          verbose = true
          EOF
          
          # Create credentials file
          mkdir -p ~/.cargo/credentials.d
          cat > ~/.cargo/credentials << EOF
          [registry]
          token = "$CARGO_REGISTRY_TOKEN"
          
          [registries]
          quantum-forge = "$CARGO_REGISTRY_TOKEN"
          EOF
          
          # Secure the credentials file
          chmod 600 ~/.cargo/credentials
          
          # Show config for debugging
          cat ~/.cargo/config.toml
      
      - name: Debug Git Tags and Environment
        run: |
          echo "Current git tags at HEAD:"
          git tag --points-at HEAD || echo "No tags found"
          echo "CARGO_REGISTRY_TOKEN exists: ${{ env.CARGO_REGISTRY_TOKEN != '' }}"
          
      - name: Publish crates
        id: publish
        run: |
          # Set a default exit code
          EXIT_CODE=0
          
          # Process the tags
          CRATES_TO_PUBLISH=$(git tag --points-at HEAD | sed 's|^[^/]*@|@|' | sed 's|^[^/]*/||' | sed 's|@.*||')
          
          if [ -z "$CRATES_TO_PUBLISH" ]; then
            echo "No crates found to publish from tags"
            
            # Check if this is a push to main or a merged PR
            if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
              echo "This is a push to main branch - publishing livekit to registry"
              # For push events, we'll publish the livekit crate for testing
              cd livekit && cargo publish --no-verify --registry quantum-forge --allow-dirty --token "$CARGO_REGISTRY_TOKEN" || EXIT_CODE=$?
              
              # Record that we published livekit
              echo "published_crates=livekit" >> $GITHUB_OUTPUT
            elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
              echo "This is a merged PR to main branch - publishing livekit to registry"
              cd livekit && cargo publish --no-verify --registry quantum-forge --allow-dirty --token "$CARGO_REGISTRY_TOKEN" || EXIT_CODE=$?
              
              # Record that we published livekit
              echo "published_crates=livekit" >> $GITHUB_OUTPUT
            else
              echo "Skipping publishing for non-push, non-merged PR, or non-main branch events"
            fi
          else
            # Publish crates based on tags
            for CRATE in $CRATES_TO_PUBLISH; do
              echo "Publishing crate: $CRATE"
              cd "$CRATE" && cargo publish --no-verify --registry quantum-forge --token "$CARGO_REGISTRY_TOKEN" || EXIT_CODE=$?
              cd ..
            done
          fi
          
          exit $EXIT_CODE
  
  create_releases:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: write
    # This job will always run and create at least a test release
    steps:
      - uses: actions/checkout@v3
      - name: Create GitHub releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISHED_CRATES: ${{ needs.publish.outputs.published_crates }}
        run: |
          echo "Crates from previous job: ${PUBLISHED_CRATES}"
          
          # Always create a test release with a timestamp to ensure the workflow is working
          TIMESTAMP=$(date "+%Y%m%d-%H%M%S")
          TEST_RELEASE_TAG="test-quantum-forge-${TIMESTAMP}"
          
          echo "Creating test release with tag: ${TEST_RELEASE_TAG}"
          gh release create "${TEST_RELEASE_TAG}" \
            --title "Test Quantum Forge Registry Release (${TIMESTAMP})" \
            --notes "This is a test release to verify the GitHub Actions workflow for quantum-forge registry.\n\nTimestamp: ${TIMESTAMP}\n\nPublished crates: ${PUBLISHED_CRATES:-None}" \
            --target main
          
          if [ -z "$PUBLISHED_CRATES" ]; then
            echo "No crates were published. Only created test release."
          else
            # Process actual published crates
            for crate in $PUBLISHED_CRATES; do
              echo "Processing release for crate: $crate"
              
              if [ -f "$crate/CHANGELOG.md" ]; then
                version=$(grep -m 1 "^##" "$crate/CHANGELOG.md" | sed 's/^## //')
                changelog=$(awk '/^## /{if (p) {exit}; p=1; next} p' "$crate/CHANGELOG.md")
              else
                version=$(grep -m 1 "version" "$crate/Cargo.toml" | cut -d'"' -f2)
                changelog="Release of $crate version $version to quantum-forge registry"
              fi
              
              echo "Creating release for $crate@$version"
              
              gh release create "$crate@$version" \
                --title "$crate $version" \
                --notes "$changelog" \
                --target main || echo "Failed to create release for $crate"
            done
          fi
