# Copyright 2023 LiveKit, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Bump and publish crates

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "packages to bump (comma-separated list)"
        type: string
        required: true

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

jobs:
  bump:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.NANPA_KEY }}
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        
      - name: Prepare packages for ilo
        id: prepare_packages
        run: |
          # Create an array from comma-separated list
          IFS=',' read -ra PKG_ARRAY <<< "${{ github.event.inputs.packages }}"
          
          # Convert to JSON format
          JSON_ARRAY=$(printf '%s\n' "${PKG_ARRAY[@]}" | jq -R . | jq -s .)
          echo "Formatted packages JSON: $JSON_ARRAY"
          
          # Save to a file that ilo can read
          echo "$JSON_ARRAY" > packages.json
          
      - name: Debug packages.json content
        run: cat packages.json
          
      - uses: nbsp/ilo@v1
        with:
          packages-file: ./packages.json
  publish:
    runs-on: ubuntu-latest
    needs: bump
    permissions:
      contents: write
    outputs:
      published_crates: ${{ steps.collect_published.outputs.published_crates }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Resync is needed after bump
        run: |
          git fetch --tags && git checkout origin/main
      - name: Configure Cargo Registry
        run: |
          mkdir -p ~/.cargo
          echo '[registries.quantum-forge]' >> ~/.cargo/config.toml
          echo 'index = "https://crate-registry.quantum-forge.io"' >> ~/.cargo/config.toml
          cat ~/.cargo/config.toml
          
      - name: Debug Git Tags and Environment
        run: |
          echo "Current git tags at HEAD:"
          git tag --points-at HEAD || echo "No tags found"
          echo "CARGO_REGISTRY_TOKEN exists: ${{ env.CARGO_REGISTRY_TOKEN != '' }}"
          
      - name: List crates to publish
        id: collect_published
        run: |
          CRATES=$(git tag --points-at HEAD | sed 's|^[^/]*@|@|' | sed 's|^[^/]*/||' | sed 's|@.*||' | tr '\n' ' ')
          echo "Found crates to publish: ${CRATES}"
          echo "published_crates=${CRATES}" >> $GITHUB_OUTPUT
          
      - name: Publish crates
        run: |
          # Set a default exit code
          EXIT_CODE=0
          
          # Process the tags
          CRATES_TO_PUBLISH=$(git tag --points-at HEAD | sed 's|^[^/]*@|@|' | sed 's|^[^/]*/||' | sed 's|@.*||')
          
          if [ -z "$CRATES_TO_PUBLISH" ]; then
            echo "No crates found to publish"
            # Create a dummy crate just for testing
            echo "TESTING: Would publish livekit to quantum-forge"
            # Uncomment the line below for actual testing
            # cd livekit && cargo publish --no-verify --registry quantum-forge || EXIT_CODE=$?
          else
            # Publish each crate individually
            for CRATE in $CRATES_TO_PUBLISH; do
              echo "Publishing crate: $CRATE"
              cd "$CRATE" && cargo publish --no-verify --registry quantum-forge || EXIT_CODE=$?
              cd ..
            done
          fi
          
          exit $EXIT_CODE
  
  create_releases:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: write
    # This job will always run and create at least a test release
    steps:
      - uses: actions/checkout@v3
      - name: Create GitHub releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISHED_CRATES: ${{ needs.publish.outputs.published_crates }}
        run: |
          echo "Crates from previous job: ${PUBLISHED_CRATES}"
          
          # Always create a test release with a timestamp to ensure the workflow is working
          TIMESTAMP=$(date "+%Y%m%d-%H%M%S")
          TEST_RELEASE_TAG="test-quantum-forge-${TIMESTAMP}"
          
          echo "Creating test release with tag: ${TEST_RELEASE_TAG}"
          gh release create "${TEST_RELEASE_TAG}" \
            --title "Test Quantum Forge Registry Release (${TIMESTAMP})" \
            --notes "This is a test release to verify the GitHub Actions workflow for quantum-forge registry.\n\nTimestamp: ${TIMESTAMP}\n\nPublished crates: ${PUBLISHED_CRATES:-None}" \
            --target main
          
          if [ -z "$PUBLISHED_CRATES" ]; then
            echo "No crates were published. Only created test release."
          else
            # Process actual published crates
            for crate in $PUBLISHED_CRATES; do
              echo "Processing release for crate: $crate"
              
              if [ -f "$crate/CHANGELOG.md" ]; then
                version=$(grep -m 1 "^##" "$crate/CHANGELOG.md" | sed 's/^## //')
                changelog=$(awk '/^## /{if (p) {exit}; p=1; next} p' "$crate/CHANGELOG.md")
              else
                version=$(grep -m 1 "version" "$crate/Cargo.toml" | cut -d'"' -f2)
                changelog="Release of $crate version $version to quantum-forge registry"
              fi
              
              echo "Creating release for $crate@$version"
              
              gh release create "$crate@$version" \
                --title "$crate $version" \
                --notes "$changelog" \
                --target main || echo "Failed to create release for $crate"
            done
          fi
